<a href="https://colab.research.google.com/github/Shinoj28/DL/blob/main/matrix_multiplication_and_finding_Eigen_vectors_and_Eigen_values_using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

x= tf.constant([1,2,3,4,5,6],shape=[2,3])
print(x)
y= tf.constant([7,8,9,10,11,12],shape=[3,2])
print(y)

z= tf.matmul(x,y)
print("\n")
print("Multiplying the matrices: ")
print(z)
print("\n")

e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("\n")
print("Matrix A: \n{}\n\n".format(e_matrix_A))

eigan_values_A,eigan_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigan Vectors: \n{}\n\nEigan Values: \n{}\n\n".format(eigan_vectors_A,eigan_values_A))



tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


Multiplying the matrices: 
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)




Matrix A: 
[[9.995829  7.1034417]
 [8.370665  4.817993 ]]


Eigan Vectors: 
[[-0.593517    0.80482143]
 [ 0.80482143  0.593517  ]]

Eigan Values: 
[-1.3549678 16.168789 ]


